blank_issues_enabled: false

contact_links:
  - name: GBAStation Repository
    url: https://github.com/GBAStationhq/GBAStation/issues
    about: Report bugs related to the GBAStation frontend, launcher, UI, downloads, or game library.

  - name: Discord
    url: https://discord.gg/DPgXGqJMkJ
    about: Questions, support, and general discussion.